# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Score Evaluation
#'
#' After applying polygenic risk score estimation tools, score evaluation for generating diagnostic plots
#'
#' @param fileName directory path of PRS result(e.g. prscs)
#' @param N Number of samples (fam)
#' @param P Number of variants (bim)
#' @param input Weight matrix for multiplication
#' @param extract logical vector indicating variants to be scored
#' @param keep logical vector indicating samples to be scored
#' @keywords internal
scorebed <- function(fileName, N, P, input, extract, keep) {
    .Call('_OAPRS_scorebed', PACKAGE = 'OAPRS', fileName, N, P, input, extract, keep)
}

